#!/usr/bin/env python3
"""
build_kg.py — Generate a Learning-Commons-style curriculum knowledge graph
(nodes.jsonl + relationships.jsonl) from your own structured curriculum data.

The output matches the schema of the existing graph:
  node   -> {"type":"node","identifier",...,"labels":[...],"properties":{...}}
  rel    -> {"type":"relationship","identifier",...,"label",...,"properties":{...},
             "source_identifier","source_labels","target_identifier","target_labels"}

Key design rule (reverse-engineered from the data):
  Every identifier is a DETERMINISTIC UUID5. Same input string -> same id, every
  run. That makes rebuilds idempotent and lets an edge reference a node by
  recomputing its id instead of needing a lookup table.
"""
import json, uuid

# One stable namespace per provider. Never change it once you've published ids.
NS = uuid.uuid5(uuid.NAMESPACE_URL, "https://your-org.example/curriculum")

PROVIDER = "Your Org"
AUTHOR   = "Your Curriculum Team"
LICENSE  = "https://creativecommons.org/licenses/by/4.0/"
ATTRIB   = "Knowledge Graph generated by Your Org."

def nid(kind, native_key):
    """Deterministic content id, e.g. nid('Lesson','math3:u2:l11')."""
    return "yo:" + str(uuid.uuid5(NS, f"{kind}|{native_key}"))

def case_uuid(framework, native_key):
    """Standards items are keyed by caseIdentifierUUID (the CASE standard)."""
    return str(uuid.uuid5(NS, f"CASE|{framework}|{native_key}"))

nodes, rels = [], []

def node(identifier, label, **props):
    props.setdefault("identifier", identifier)
    props.update(provider=PROVIDER, author=AUTHOR, license=LICENSE,
                 attributionStatement=ATTRIB, inLanguage="en-US")
    nodes.append({"type":"node","identifier":identifier,
                  "labels":[label],"properties":props})
    return identifier

def rel(label, s_id, s_label, t_id, t_label, s_key="identifier",
        t_key="identifier", **props):
    ident = str(uuid.uuid5(NS, f"{label}|{s_id}|{t_id}"))   # deterministic edge id
    props.update(identifier=ident, relationshipType=label, provider=PROVIDER,
                 author=AUTHOR, license=LICENSE, attributionStatement=ATTRIB,
                 sourceEntity=s_label, targetEntity=t_label,
                 sourceEntityKey=s_key, targetEntityKey=t_key)
    rels.append({"type":"relationship","identifier":ident,"label":label,
                 "properties":props,
                 "source_identifier":s_id,"source_labels":[s_label],
                 "target_identifier":t_id,"target_labels":[t_label]})

# ─────────────────────────────────────────────────────────────────────────────
# 1) STANDARDS SIDE — usually imported from a CASE framework (1EdTech CASE JSON).
#    Here, a tiny hand-built example: framework -> item -> child item.
# ─────────────────────────────────────────────────────────────────────────────
FW = "OH-Math"
fw_id = case_uuid(FW, "__root__")
node(fw_id, "StandardsFramework", name="Ohio Math Learning Standards",
     academicSubject="Mathematics", jurisdiction="Ohio",
     caseIdentifierUUID=fw_id, caseIdentifierURI=f"https://example/case/{fw_id}")

std_parent = case_uuid(FW, "7.SP")
node(std_parent, "StandardsFrameworkItem", description="Statistics & Probability",
     academicSubject="Mathematics", jurisdiction="Ohio", gradeLevel='["7"]',
     caseIdentifierUUID=std_parent, caseIdentifierURI=f"https://example/case/{std_parent}")
rel("hasChild", fw_id, "StandardsFramework", std_parent, "StandardsFrameworkItem",
    s_key="caseIdentifierUUID", t_key="caseIdentifierUUID")

std_child = case_uuid(FW, "7.SP.A.1")
node(std_child, "StandardsFrameworkItem",
     description="Understand statistics: sampling & inference",
     academicSubject="Mathematics", jurisdiction="Ohio", gradeLevel='["7"]',
     caseIdentifierUUID=std_child, caseIdentifierURI=f"https://example/case/{std_child}")
rel("hasChild", std_parent, "StandardsFrameworkItem", std_child, "StandardsFrameworkItem",
    s_key="caseIdentifierUUID", t_key="caseIdentifierUUID")

# ─────────────────────────────────────────────────────────────────────────────
# 2) CONTENT SIDE — Course -> LessonGrouping (unit) -> Lesson -> Activity/Assessment
# ─────────────────────────────────────────────────────────────────────────────
course = nid("Course","math7")
node(course, "Course", name="Grade 7 Mathematics", courseCode="yo:math7",
     academicSubject="Mathematics", gradeLevel='["7"]', curriculumLabel="Course")

unit = nid("LessonGrouping","math7:u2")
node(unit, "LessonGrouping", name="Unit 2: Sampling", courseCode="yo:math7",
     groupName="Unit", groupLevel="1", position="2", ordinalName="Unit 2",
     academicSubject="Mathematics", gradeLevel='["7"]', curriculumLabel="Unit")
rel("hasPart", course, "Course", unit, "LessonGrouping")

lesson = nid("Lesson","math7:u2:l11")
node(lesson, "Lesson", name="Estimating a Population Mean", courseCode="yo:math7",
     position="11", ordinalName="Lesson 11", timeRequired="PT45M",
     academicSubject="Mathematics", gradeLevel='["7"]', curriculumLabel="Lesson")
rel("hasPart", unit, "LessonGrouping", lesson, "Lesson")

act = nid("Activity","math7:u2:l11:a1")
node(act, "Activity", name="Warm-up: What's a fair sample?", position="1",
     timeRequired="PT10M", academicSubject="Mathematics", curriculumLabel="Activity")
rel("hasPart", lesson, "Lesson", act, "Activity")

asm = nid("Assessment","math7:u2:l11:cooldown")
node(asm, "Assessment", name="Cool-down: Estimate the mean",
     academicSubject="Mathematics", curriculumLabel="Cool-down",
     gradingRequired="false", submissionRequired="true")
rel("hasPart", lesson, "Lesson", asm, "Assessment")

# ─────────────────────────────────────────────────────────────────────────────
# 3) THE BRIDGE — align content to standards (this is what forms the "core").
#    Note target key is caseIdentifierUUID, matching the standards item.
# ─────────────────────────────────────────────────────────────────────────────
rel("hasEducationalAlignment", lesson, "Lesson", std_child, "StandardsFrameworkItem",
    t_key="caseIdentifierUUID", alignmentType="teaches",
    curriculumAlignmentType="addressing")
rel("hasEducationalAlignment", act, "Activity", std_child, "StandardsFrameworkItem",
    t_key="caseIdentifierUUID", alignmentType="teaches",
    curriculumAlignmentType="addressing")

# optional: LearningComponent -> supports -> standard
lc = nid("LearningComponent","lc:sampling-mean")
node(lc, "LearningComponent", description="Estimate a population mean from a sample",
     academicSubject="Mathematics", examples="[]")
rel("supports", lc, "LearningComponent", std_child, "StandardsFrameworkItem",
    t_key="caseIdentifierUUID")

# ─────────────────────────────────────────────────────────────────────────────
# WRITE
# ─────────────────────────────────────────────────────────────────────────────
with open("nodes.new.jsonl","w") as f:
    for n in nodes: f.write(json.dumps(n)+"\n")
with open("relationships.new.jsonl","w") as f:
    for r in rels: f.write(json.dumps(r)+"\n")
print(f"wrote {len(nodes)} nodes -> nodes.new.jsonl")
print(f"wrote {len(rels)} edges -> relationships.new.jsonl")
